#include<stdio.h>

void hailstone(int i){
	int count=0,sum=1;
		while(1){
		if(i%2&&i!=1){
			printf("%4d",i);
			count++;
			i=3*i+1;
		}
		else{
			printf("%4d",i);
			count++;
			i=i/2;
		}

		if(count==6){
			count=0;
			putchar('\n');
		}
		sum++;
		if(i==1){
			printf("%4d",i);
			break;
		}
	}
	printf("\nNumber of hailstone generated: %d",sum);
}

int main(void){
	int i;
	scanf("%d",&i);
	printf("Hailstone generated by %d:\n",i);
	hailstone(i);
	return 0;
} 

